### ISSUE TITLE
Community Verification of Tauri & Servo Integration

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/wry#1153]
We currently have a [branch](https://github.com/tauri-apps/wry/tree/servo-wry-demo) for experimenting servo integration. Servo also has a [blog post](https://servo.org/blog/2024/01/19/embedding-update/) about it.
If anyone is interested, please help us test if it works well on each platform.

Here are prerequisites for each platform:

### Windows

- Install [scoop](https://scoop.sh/) and then install other tools from it. You can install them manually but this is easier:

```sh
scoop install git python llvm cmake curl
```

### MacOS

- Install [Xcode](https://developer.apple.com/xcode/)
- Install [Homebrew](https://brew.sh/) and then run:

```sh
brew install cmake pkg-config
```

### Linux

For now, please follow the instructions in [Servo - Build Setup](https://github.com/servo/servo) to bootstrap first.
And it only works on x11 at the moment. Wayland or Xwayland won't work.

### Run Demo

```
cargo r --example servo
```

**Comment by tensor-programming** [comment]
Builds and runs on Windows 11 build 2263

![image](https://github.com/tauri-apps/wry/assets/22513880/444cc7c5-7c92-4f55-a375-f0817a14ae2b)

Will also check WSL2 ubuntu tomorrow.

edit: the servo instructions do not mention installing cmake and pkconfig. Tried WSL but am still having errors with pkg-config not finding the font lib.  Will mess with it some more and get back.

**Comment by daniel-mader** [comment]
I'm a developer [@impierce](https://github.com/impierce) and I can confirm it works on macOS 14, `rustc 1.75.0`

**Comment by Norlock** [comment]
It doesn't work on my machine, I use Arch btw ;). 

Running on Wayland (sway).

```shell
Finished dev [unoptimized + debuginfo] target(s) in 9m 21s
     Running `target/debug/examples/servo`
servo: ../wayland-1.22.0/src/wayland-client.c:2377: wl_proxy_set_queue: Assertion `proxy->display == queue->display' failed.
fish: Job 1, 'cargo r --example servo' terminated by signal SIGABRT (Abort)
```

**Comment by adriantombu** [comment]
![Screenshot 2024-01-26 at 11 56 25](https://github.com/tauri-apps/wry/assets/383297/943b04dc-a823-4943-a0c9-b2e0eb9165d8)

The branch `servo-wry-demo` Works on my machine™ running on `macOs 13.6` with `rustc 1.74.1`, nice work!

**Comment by nanderstabel** [comment]
Developer from [@impierce](https://github.com/impierce) here. I can also confirm it works for me (Ubuntu 22.04, after using X11 instead of Wayland).

![Screenshot from 2024-01-26 13-39-53](https://github.com/tauri-apps/wry/assets/50104940/190a4440-dbd9-440b-88f9-a53087b7545b)

**Comment by Mikopet** [comment]
Hey!

My main issue on Linux setup is building the `mozangle`. (So far every other system dependencies I was able to pull from `apt`)
The issue comes down to:
```
  gfx/angle/checkout/include/GLSLANG/ShaderLang.h:13:10: fatal error: 'array' file not found
  thread 'main' panicked at /home/mikopet/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/build.rs:333:10:
  Should generate shader bindings: ClangDiagnostic("gfx/angle/checkout/include/GLSLANG/ShaderLang.h:13:10: fatal error: 'array' file not found\n")
```

It is probably the result of improper "servo bootstrapping", which has a system dependency conflict on `harfbuzz`.
```
The following packages have unmet dependencies:
libharfbuzz-dev :
    Depends: libharfbuzz0b (= 2.7.4-1ubuntu3.1) but 6.0.0+dfsg-3+22.04+jammy+release+build1 is to be installed
    Depends: libharfbuzz-icu0 (= 2.7.4-1ubuntu3.1) but 6.0.0+dfsg-3+22.04+jammy+release+build1 is to be installed
    Depends: gir1.2-harfbuzz-0.0 (= 2.7.4-1ubuntu3.1) but 6.0.0+dfsg-3+22.04+jammy+release+build1 is to be installed
```

Now, my system is a tuxedo OS, which is a fork of `Ubuntu 22.04`, but have more fresh libharfbuzz because of some system tools. (also it does not use the ubuntu repositories)

I have overcome on the problem with compiling from source, so I had to install a few dev dependencies for building a `.deb` (I wasn't able to download them from package registry):
```bash
# install of build dependencies
sudo apt install debhelper-compat libglib2.0-dev libcairo2-dev libgraphite2-dev libgirepository1.0-dev gobject-introspection gtk-doc-tools
# build the .deb, install the package
apt-get source --compile libharfbuzz-dev
dpkg -i libharfbuzz-dev_2.7.4-1ubuntu3.1_amd64.deb
```

Well, this approach broke my apt completely, so **DO NOT** do this way.
However, after recovering and let some packages gone forever (also majority of the i386 packages on amd cpu...)  ...
... servo bootstrapped.
... servo compile failed on `fontsan`

solution:
```
sudo apt install libstdc++-12-dev
```

... took ages, but servo compiled.
... wry compiled.

**App is running!** (so it's definitely doable)

Now I'm going to restart the system, wish me luck :sweat_smile:

**Comment by queer** [comment]
Builds and runs on latest Arch Linux with Rust 1.75.0 
![image](https://github.com/tauri-apps/wry/assets/23562067/7b9c7d23-775f-4f70-8b9f-93e74537e46b)

**Comment by JelleMillenaar** [comment]
Another [@Impierce](https://github.com/impierce) checking in and it worked flawlessly on Windows 10 Pro OS Build 19045.3930.
![image](https://github.com/tauri-apps/wry/assets/29886335/81ca9471-5570-49ba-a7e2-8fde2e5fe681)

**Comment by timClicks** [comment]
I'm not sure if I'm being blind, but I can't find the `servo` example in the `servo-wry-demo` branch. Is it possible to be more explicit on where this should be invoked?

``` console
$ cargo run --example servo
error: no example target named `servo`.
Available example targets:
    simple
    gtk_multiwebview
    transparent
    winit
    custom_titlebar
    async_custom_protocol
    multiwindow
    wgpu
    custom_protocol
    multiwebview


$ git branch
  dev
* origin/servo-wry-demo
```

I'm running Ubuntu 20.04.

**Comment by amrbashir** [comment]
@timClicks this is the example https://github.com/tauri-apps/wry/blob/servo-wry-demo/examples/servo.rs

Can you check  which commit your branch is on? because it seems like you checkout out a new branch called `origin/servo-wry-demo` instead of checking out the existing branch but I am just speculating here.

**Comment by timClicks** [comment]
That's very likely! I wondered if I had made a mistake. Thank you for getting back to me.

**Comment by wijjj** [comment]
I also tried the demo on my Linux system. **It works!** 😍
Specs of my system first:

- Ubuntu 22.04.3 LTS (to be more precisde: Kubuntu)
- rustc 1.75.0 (82e1608df 2023-12-21)
- cargo 1.75.0 (1d8b05cdd 2023-11-20)
- Python 3.10.12
- OpenGL version string: 4.6.0 NVIDIA 535.104.05
- XDG_SESSION_TYPE=x11

As instructed I first built `servo` and at least `./mach bootstrap` just ran through without producing errors.

Then I checked out the `servo-wry-demo` feature branch, attempted to run `cargo r --example servo` and it broke. Same issue that @Mikopet mentioned: building mozangle 0.5.0 failed. I'm attaching the complete output in a text file here with `CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true RUST_BACKTRACE=full`:
[cargo_r_example_servo_backtrace_2.txt](https://github.com/tauri-apps/wry/files/14070121/cargo_r_example_servo_backtrace_2.txt)

Finally I was also able to solve the problem by installing `libstdc++-12-dev` manually via apt, as @Mikopet described (btw big thanks, saved my evening! :)

![2024-01-27_00-29](https://github.com/tauri-apps/wry/assets/726919/a54d47bb-62b0-4f48-b3a8-07f18db9d78b)

Let's goooooooooooooooooo

**Comment by timClicks** [comment]
Thank you @amrbashir, you were correct 🤦🏻‍♂️.

- Ubuntu 20.04.4 LTS
- X11
- Rust 1.74

Unlike the other Linux users in this thread, I didn't have any issues with finding dev packages. Let me know if there are other system parameters that I should provide.


https://github.com/tauri-apps/wry/assets/27889/5d5cfd2a-ccae-4621-b8d8-20b5d00cbec8


ug/examples/servo`


The [build log is available](https://github.com/tauri-apps/wry/files/14070374/build-log.txt) if you are curious.

**Comment by lemarier** [comment]
Hello 👋 built on `Mac14,13` with the `Apple M2 Max` chip, toolchain `1.74-aarch64-apple-darwin`.

`Finished dev [unoptimized + debuginfo] target(s) in 4m 59s`

Built was smooth! Well done (again) 💋 


***

<img width="592" alt="Screenshot 2024-01-27 at 12 43 34 PM" src="https://github.com/tauri-apps/wry/assets/22237916/b10b6cd6-687e-4a18-8035-5a8d0d2b2c06">

**Comment by rhysd** [comment]
I encountered a small build error on building `servo` example. But after fixing it, I could confirm both release and debug builds worked well! I created a PR for the fix: https://github.com/tauri-apps/wry/pull/1157

<img width="612" alt="screenshot" src="https://github.com/tauri-apps/wry/assets/823277/b3d3529a-7e6b-4057-a63f-11553c0971d2">

My environment is:

- macOS 13 on Intel Mac
- Rust 1.74.1
- Xcode 15.0.1

**Comment by AZProductions** [comment]
Any plans for open_servo_parented?

**Comment by salluzziluca** [comment]
Hi, Im getting the following error on fedora 40

```bash
cargo r --example servo
   Compiling mozangle v0.5.0
error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangInitialize` in this scope
  --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:29:17
   |
29 |     if unsafe { GLSLangInitialize() } == 0 {
   |                 ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangFinalize` in this scope
  --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:37:17
   |
37 |     if unsafe { GLSLangFinalize() } == 0 {
   |                 ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangInitBuiltInResources` in this scope
   --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:114:13
    |
114 |             GLSLangInitBuiltInResources(&mut ret);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangConstructCompiler` in this scope
   --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:167:13
    |
167 |             GLSLangConstructCompiler(
    |             ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangCompile` in this scope
   --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:210:13
    |
210 |             GLSLangCompile(
    |             ^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangGetObjectCode` in this scope
   --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:225:40
    |
225 |             let c_str = CStr::from_ptr(GLSLangGetObjectCode(self.handle));
    |                                        ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangGetInfoLog` in this scope
   --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:232:40
    |
232 |             let c_str = CStr::from_ptr(GLSLangGetInfoLog(self.handle));
    |                                        ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangIterUniformNameMapping` in this scope
   --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:289:13
    |
289 | ...   GLSLangIterUniformNameMapping(self.handle, Some(each_c), closure_...
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangGetNumUnpackedVaryingVectors` in this scope
   --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:298:18
    |
298 |         unsafe { GLSLangGetNumUnpackedVaryingVectors(self.handle) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GLSLangDestructCompiler` in this scope
   --> /home/kvothe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozangle-0.5.0/src/shaders/mod.rs:304:18
    |
304 |         unsafe { GLSLangDestructCompiler(self.handle) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `mozangle` (lib) due to 10 previous errors
```

I can run servoshell normally so its not that I havent done the boostrap setup. Ive also installed glslang via dnf `sudo dnf install glslang
`

**Comment by spookyvision** [comment]
> Hi, Im getting the following error on fedora 40

I have the same problem in pop!Os (based on Ubuntu). Sadly no idea how to fix.

**Comment by spookyvision** [comment]
after fighting compiler+linker for quite a while I managed to get a successful build, but it crashes in both debug and release mode, so I'm giving up.

```
servo: ../src/wayland-client.c:2460: wl_proxy_set_queue: Assertion `proxy->display == queue->display' failed.
zsh: IOT instruction (core dumped)  RUST_BACKTRACE=1 cargo run --example servo
```

sadly I also accidentally reverted my changes so I can't provide a diff, but what I do remember is that I had to remove the bindgen-f16 patch and override a few dependencies with local clones (using both `Cargo.toml` and `.cargo/config.toml` `paths=`), patching their `Cargo.toml`s so that everything uses `bindgen=0.71.1` (which has f16 support added). For `mozangle` I specifically took the `0.5.2` tag.
